<style>
	body{
		color: #2F4F4F;
	    font-family: 'Raleway',sans-serif;	
	}
	.input-div{
		margin: 10 auto;
		width: 200px;
	}
	.button-div{
		margin: 10 auto;
		width: 75px;
	}
	.input{
		padding: 2px;
		height: 30px;
		width: 200px;
	}
	#add-user{
		background-color: #dcdcdc;
		border: 1px solid #999;
		height: 30px;
		width: 75px;
	}
	#error-message{
		background-color: #ff0033; 
		color: #fff;
		display: none;
		margin: 10 auto; 
		padding: 5px; 
		width: 190px; 
		white-space: normal;
	}
	.missing-val{
		border: 1px solid #ff0033;
		padding: 3px;
	}
	.input-check{
		padding: 20px 0;
	}
	#checkbox{
		background-color: #fff;
		height: 40px;
		width: 40px;
		margin-bottom: 10px;
	}
	#title{
		background-color: #707070;
		background: -webkit-linear-gradient(#707070, #f6f6f6); /* For Safari 5.1 to 6.0 */
	    background: -o-linear-gradient(#707070, #f6f6f6); /* For Opera 11.1 to 12.0 */
	    background: -moz-linear-gradient(#707070, #f6f6f6); /* For Firefox 3.6 to 15 */
	    background: linear-gradient(#707070, #f6f6f6); /* Standard syntax */
		height: 100px;
		padding-top: 10px;
		text-align: center;
	}
	#content{
		background-color: #f6f6f6;
		height: calc(100% - 130px);
		padding-top: 16px;
		text-align: center;
	}
</style>
<div id="title">
	<h1>ADD</h1>
</div>
<div id="content">
	<div id="error-message">
	</div>
	<div class="input-div">
		<input id="email" class="input" type="text" placeholder="Email">
	</div>
	<div class="input-div">
		<input id="username" class="input" type="text" placeholder="Username">
	</div>
	<!-- CSFR prevention -->
	<div class="input-check">
		<input id="checkbox" type="checkbox">
		<div>CHECK IF YOUR A HUMAN</div> 
	</div>
	<!-- /CSFR prevention-->
	<div class="button-div">
		<input id="add-user" type="button" value="Add User" style="cursor: pointer;" disabled>
	</div>
</div>

<!-- Import jQuery library -->
<script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<!-- /Import jQuery library -->
<script>
	$("#checkbox").click(function(){
		if($(this).is(":checked")){
			$("#add-user").removeAttr("disabled");
		} else {
			$("#add-user").attr("disabled", "disabled");
		}
	});

	$("#add-user").click(function(e){
		$("#error-message").fadeOut();
		var email = $("#email").val();
		var username = $("#username").val();

		// if any value is missing its input will be highlighted
		if (email === "" || username === "") {
			if (email === "") {
				$("#email").addClass("missing-val");
			} else {
				$("#email").removeClass("missing-val");
			}

			if (username === "") {
				$("#username").addClass("missing-val");
			} else {
				$("#username").removeClass("missing-val");
			}
		// if all the input are filled than test the email value
		} else {
			$("#email").removeClass("missing-val");
			$("#username").removeClass("missing-val");

			// test the email to the regex 
			var re = /^(([^<>()[\]\.,;:\s@\"]+(\.[^<>()[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/i;
			// if email invalid show error message if not than make the call
			if(!re.test($("#email").val())){
				$("#error-message").text("Error! Email invalid.").fadeIn("slow");
			} else {
				var url = "/public/home/addrecord/" + email + "/" + username;
				$.ajax({
					url: url,
					dataType: 'json',
					type: 'post',
					success: function(data) {
						// in case the sql insert was completed successfully than sow success message
						// if not than show error message
						if (data['status'] === 'success') {
							$("#error-message").css("background-color", "#66cd00").text("User added with success!").fadeIn("slow");
							$("#email").val("");
							$("#username").val("");
							$("#checkbox").click();
						} else {
							$("#error-message").text("Error! " + data['message']).fadeIn("slow");
						}
					}
				});
			}	
		}
	});
</script>