<link href="/css/add.css" rel="stylesheet">

<div id="title">
	<h1>ADD</h1>
</div>
<div id="content">
	<div id="error-message">
	</div>
	<div class="input-div">
		<input id="email" class="input" type="text" placeholder="Email">
	</div>
	<div class="input-div">
		<input id="username" class="input" type="text" placeholder="Username">
	</div>
	<!-- CSFR prevention -->
	<div class="input-check">
		<input id="checkbox" type="checkbox">
		<div>CHECK IF YOUR A HUMAN</div> 
	</div>
	<!-- /CSFR prevention-->
	<div class="button-div">
		<input id="add-user" type="button" value="Add User" style="cursor: pointer;" disabled>
	</div>
</div>

<!-- Import jQuery library -->
<script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<!-- /Import jQuery library -->

<script src="/js/add.js"></script>