<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<style>
	.material-icons {
	  font-family: 'Material Icons';
	  font-weight: normal;
	  font-style: normal;
	  font-size: 20px;  /* Preferred icon size */
	  display: inline-block;
	  width: 1em;
	  height: 1em;
	  line-height: 1;
	  text-transform: none;
	  letter-spacing: normal;
	  word-wrap: normal;
	  white-space: nowrap;
	  direction: ltr;

	  /* Support for all WebKit browsers. */
	  -webkit-font-smoothing: antialiased;
	  /* Support for Safari and Chrome. */
	  text-rendering: optimizeLegibility;

	  /* Support for Firefox. */
	  -moz-osx-font-smoothing: grayscale;

	  /* Support for IE. */
	  font-feature-settings: 'liga';
	}
	body{
		color: #2F4F4F;
		font-family: 'Raleway',sans-serif;
	}
	#title{
		background-color: #707070;
		background: -webkit-linear-gradient(#707070, #f6f6f6); /* For Safari 5.1 to 6.0 */
	    background: -o-linear-gradient(#707070, #f6f6f6); /* For Opera 11.1 to 12.0 */
	    background: -moz-linear-gradient(#707070, #f6f6f6); /* For Firefox 3.6 to 15 */
	    background: linear-gradient(#707070, #f6f6f6); /* Standard syntax */
		height: 100px;
		padding-top: 10px;
		text-align: center;
	}
	#content{
		background-color: #f6f6f6;
		height: calc(100% - 130px);
		padding-top: 16px;
		text-align: center;
	}
	a{
		color: #551a8b;
		text-decoration: none;
	}
</style>

<div id="title">
	<h1>HELLO WORLD!</h1>
</div>
<div id="content">
	<h3>Welcome to my php challenge by Seedstars and executed by Elton Morais, yes, myself!</h3>
	<div id="links" style="width: 400px; margin: 0 auto; margin-top: 50px;">
		<div style="width: 200px;float: left;">
			<div style="float: left;padding-left: 15px;margin-top: -2px;">
				<i class="material-icons" style="position:absolute;">note_add</i>
			</div> 
			<a href="/public/home/add">Add a new client</a>
		</div>
		<div style="width: 200px;float: left;">
			<div style="float: left;padding-left: 25px;margin-top: -2px;">
				<i class="material-icons" style="position:absolute;">list</i> 
			</div>
			<a href="/public/home/listAll">List all clients</a>
		</div> 
	</div>
</div>

<script>
</script>