<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="/css/index.css" rel="stylesheet">

<div id="title">
	<h1>HELLO WORLD!</h1>
</div>
<div id="content">
	<h3>Welcome to my php challenge by Seedstars and executed by Elton Morais, yes, myself!</h3>
	<div id="links" style="width: 400px; margin: 0 auto; margin-top: 50px;">
		<div style="width: 200px;float: left;">
			<div style="float: left;padding-left: 15px;margin-top: -2px;">
				<i class="material-icons" style="position:absolute;">note_add</i>
			</div> 
			<a href="/home/add">Add a new client</a>
		</div>
		<div style="width: 200px;float: left;">
			<div style="float: left;padding-left: 25px;margin-top: -2px;">
				<i class="material-icons" style="position:absolute;">list</i> 
			</div>
			<a href="/home/listAll">List all clients</a>
		</div> 
	</div>
</div>