<link href="/css/list.css" rel="stylesheet">

<div id="title">
	<h1>LIST</h1>
</div>
<div id="content">
	<h3 style="padding-left: 10px;">All clients</h3>
	<?php 
	if (count($data["clients"]) == 0) {
		echo "<span>No clients registered</span>";
	} else {
		echo "<ul>";
		foreach($data["clients"] as $client) {
			echo "<li> <b>EMAIL:</b> " . $client[0] . "<b> | USERNAME:</b> " . $client[1] ."</li>";
		} 
		echo "</ul>";
	} ?>
</div>
