<style>
	body{
		color: #2F4F4F;
	    font-family: 'Raleway',sans-serif;	
	}
	#title{
		background-color: #707070;
		background: -webkit-linear-gradient(#707070, #f6f6f6); /* For Safari 5.1 to 6.0 */
	    background: -o-linear-gradient(#707070, #f6f6f6); /* For Opera 11.1 to 12.0 */
	    background: -moz-linear-gradient(#707070, #f6f6f6); /* For Firefox 3.6 to 15 */
	    background: linear-gradient(#707070, #f6f6f6); /* Standard syntax */
		height: 100px;
		padding-top: 10px;
		text-align: center;
	}
	#content{
		background-color: #f6f6f6;
		height: calc(100% - 130px);
		padding-top: 16px;
	}
</style>
<div id="title">
	<h1>LIST</h1>
</div>
<div id="content">
	<h3 style="padding-left: 10px;">All clients</h3>
	<?php 
	if (count($data["clients"]) == 0) {
		echo "<span>No clients registered</span>";
	} else {
		echo "<ul>";
		foreach($data["clients"] as $client) {
			echo "<li> <b>EMAIL:</b> " . $client[0] . "<b> | USERNAME:</b> " . $client[1] ."</li>";
		} 
		echo "</ul>";
	} ?>
</div>
